language:
    - objective-c

env:
    matrix:
        - python=2.7 CONDA_PY=27 CONDA_NPY=17
        - python=2.7 CONDA_PY=27 CONDA_NPY=18
        - python=2.7 CONDA_PY=27 CONDA_NPY=19

    #global:
    #    - secure: 

install: 
    - source install.sh
script:
    - conda build --quiet conda-recipe

after_success:
    - cp /Users/travis/miniconda/conda-bld/osx-64/*.tar.bz2 .
      #- binstar -t $BINSTAR_TOKEN upload --force *.tar.bz2
